version: 0.2

env:
  secrets-manager:
    DOKCERHUB_USERNAME: dockerhub:username
    DOKCERHUB_PASSWORD: dockerhub:password
  variables:
    IMAGE: rborovets/defibrillator-back
            
phases:
  install:
    commands:
      - curl -sSL https://raw.githubusercontent.com/harbur/captain/v1.1.3/install.sh | bash
      - export PATH=$HOME/.captain/bin:$PATH

  pre_build:
    commands:
      - echo Logging in to Dockerhub...
      - docker login -u $DOKCERHUB_USERNAME -p $DOKCERHUB_PASSWORD

  build:
    commands:
      - echo Build started on `date` && echo Building the Docker image...
      - docker build . -t $IMAGE
      - docker run $IMAGE echo 'Running tests'
      - docker run $IMAGE echo 'Running linters'

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - captain push -—Å